export const SESSION_START = 'SESSION_START';
export const SESSION_UPDATE_USER = 'SESSION_UPDATE_USER';
export const SESSION_CHANGE_PASSWORD = 'SESSION_CHANGE_PASSWORD';
export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_FAIL = 'SESSION_FAIL';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const SET_SESSION_REDIRECT_PATH = 'SET_SESSION_REDIRECT_PATH';


export const USERS_CREATE_START = 'USERS_CREATE_START';
export const USERS_CREATE_SUCCESS = 'USERS_CREATE_SUCCESS';
export const USERS_CREATE_FAIL = 'USERS_CREATE_FAIL';

export const USERS_LIST_START = 'USERS_LIST_START';
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
export const USERS_LIST_FAIL = 'USERS_LIST_FAIL';
